# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_score',
            name='time',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 18, 31, 26, 641135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='website',
            name='time',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 18, 31, 26, 640220, tzinfo=utc)),
        ),
    ]
