# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190505_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_score',
            name='score',
            field=models.IntegerField(choices=[(1, 'SAFE'), (0, 'NEUTRAL'), (-1, 'UNSAFE')], default=0),
        ),
        migrations.AlterField(
            model_name='feature_score',
            name='time',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 18, 49, 36, 346080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='website',
            name='time',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 18, 49, 36, 345246, tzinfo=utc)),
        ),
    ]
