# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190505_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_score',
            name='time',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 18, 49, 54, 905271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='website',
            name='time',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 18, 49, 54, 904425, tzinfo=utc)),
        ),
    ]
